{% set name = "cpd" %}
{% set version = "0.5.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/gadomski/cpd/archive/v{{ version }}.tar.gz
  sha256: 22c1ce67326f93da25a6573100d3d4d7883836f3c7c8c4fbc44c342994aaf90b

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}
    - fgt
    - make  # [unix]
    - eigen
  run:
    - eigen

test:
  commands:
    - test -f ${PREFIX}/lib/libcpd.a  # [not win]
    - if not exist %LIBRARY_LIB%\\cpd.lib exit 1  # [win]

about:
  home: https://github.com/gadomski/cpd/
  license: GPL-2.0-or-later
  license_file: LICENSE.txt
  summary: C++ implementation of the Coherent Point Drift point set registration algorithm.
  description: |
    C++ implementation of the Coherent Point Drift point set registration algorithm.
  doc_url: https://github.com/gadomski/cpd/
  dev_url: https://github.com/gadomski/cpd/

extra:
  recipe-maintainers:
    - hobu
    - chambbj
    - gadomski
